name: chest_X_ray
data_path: /home/amirh/work/reza_imrt/imrtV2/car_accessories_dataset
preload_path: /home/amirh/work/reza_imrt/imrtV2/preload_dataset
save_path: /home/amirh/work/reza_imrt/imrtV2/result
input_size: 256 # image resolution for the LPM
num_classes: 118 # number of classes
mean: [0.485, 0.456, 0.406] # 'auto' or a list of three numbers for RGB
std: [0.229, 0.224, 0.225] # 'auto' or a list of three numbers for RGB
learning_rate: 0.0005 # dataset-specific learning rate
image_channel_num: 3



# name: chest_X_ray
# data_path: /content/dataset/splited_chest_xray
# preload_path: /content/dataset/preload_chest_xray
# save_path: /content/output/result

# learning_rate: 0.0005

#old
#learning_rate: 0.0005 # dataset-specific learning rate
