name: chest_X_ray
data_path: /home/amirh/work/medical_image_classification/splited_chest_xray
preload_path: /home/amirh/work/medical_image_classification/preload_chest_xray
save_path: /home/amirh/work/medical_image_classification/result
input_size: 512 # image resolution for the LPM
num_classes: 2 # number of classes
mean: [0.5] # 'auto' or a list of three numbers for RGB
std: [0.5] # 'auto' or a list of three numbers for RGB
learning_rate: 0.0005 # dataset-specific learning rate
image_channel_num: 3

